// packages/fastboard-react/src/components/PlayerControl/components/Button.tsx
import type { Placement } from "tippy.js";
import type { Theme } from "../../../typings";

import clsx from "clsx";
import React, { forwardRef, type PropsWithChildren } from "react";
import Tippy from "@tippyjs/react";

import { TopOffset } from "../../../theme";

type ButtonProps = PropsWithChildren<{
  theme: Theme;
  content: React.ReactNode;
  disabled?: boolean;
  active?: boolean;
  onClick?: () => void;
  interactive?: boolean;
  placement?: Placement;
}>;

export const Button = forwardRef<HTMLButtonElement, ButtonProps>((props, ref) => {
  const { theme, content, disabled, active, onClick, interactive, placement = "top", children } = props;

  return (
    <Tippy
      className="fastboard-tip"
      content={content}
      interactive={interactive}
      theme={theme}
      disabled={disabled}
      placement={placement}
      offset={TopOffset}
      delay={[1000, 400]}
      duration={300}
    >
      <button
        ref={ref}
        className={clsx("fastboard-player-control-btn", theme, { active })}
        onClick={onClick}
        disabled={disabled}
      >
        {children}
      </button>
    </Tippy>
  );
});

// packages/fastboard-ui/src/components/Button/Button.svelte
<script lang="ts">
  import type { Content, Placement } from "tippy.js";
  import type { Theme } from "../../typings";
  import { tippy, tippy_menu } from "../../actions/tippy";

  let className = "";
  export { className as class };
  export let name = "fastboard-ui";
  export let theme: Theme = "light";
  export let active = false;
  export let disabled = false;
  export let content: Content = "";
  export let placement: Placement = "top";
  export let menu: Content = "";
  export let menu_placement: Placement = "right-start";
</script>

{#if content}
  {#if menu}
    <span class="{name}-btn-interactive {theme}" use:tippy={{ content, placement, className }}>
      <button
        class="{name}-btn {className} {theme}"
        class:is-active={active}
        {disabled}
        on:click
        use:tippy={{
          content: menu,
          ...tippy_menu,
          placement: menu_placement,
          appendTo: document.body,
          theme,
          className: "fastboard-panel",
        }}
      >
        <slot />
      </button>
      <span class="{name}-triangle" />
    </span>
  {:else}
    <button
      class="{name}-btn {className} {theme}"
      class:is-active={active}
      {disabled}
      on:click
      use:tippy={{ content, placement, className }}
    >
      <slot />
    </button>
  {/if}
{:else}
  <button class="{name}-btn {className} {theme}" class:is-active={active} {disabled} on:click>
    <slot />
  </button>
{/if}
