// src/components/Toolbar/components/Button.tsx
import clsx from "clsx";
import React, { useContext, type PropsWithChildren } from "react";
import Tippy from "@tippyjs/react";

import { ToolbarContext } from "../Toolbar";

interface ButtonProps {
  content: string;
  disabled?: boolean;
  active?: boolean;
  onClick?: () => void;
  interactive?: boolean;
}

const RightOffset = [0, 18] as [number, number];

export function Button({
  content,
  disabled,
  active,
  onClick,
  interactive = true,
  children,
}: PropsWithChildren<ButtonProps>) {
  const { writable, theme } = useContext(ToolbarContext);

  return (
    <Tippy
      content={content}
      interactive={interactive}
      theme={theme}
      disabled={!writable || disabled}
      placement="right"
      offset={RightOffset}
      duration={500}
    >
      <button
        className={clsx("fastboard-toolbar-btn", theme, { active })}
        onClick={onClick}
        disabled={!writable || disabled}
      >
        {children}
      </button>
    </Tippy>
  );
}

// packages/fastboard-ui/src/components/Button/Button.svelte
<script lang="ts">
  import type { Content, Placement } from "tippy.js";
  import type { Theme } from "../../typings";
  import { tippy, tippy_menu } from "../../actions/tippy";

  let className = "";
  export { className as class };
  export let name = "fastboard-ui";
  export let theme: Theme = "light";
  export let active = false;
  export let disabled = false;
  export let content: Content = "";
  export let placement: Placement = "top";
  export let menu: Content = "";
  export let menu_placement: Placement = "right-start";
</script>

{#if content}
  {#if menu}
    <span class="{name}-btn-interactive {theme}" use:tippy={{ content, placement, className }}>
      <button
        class="{name}-btn {className} {theme}"
        class:is-active={active}
        {disabled}
        on:click
        use:tippy={{
          content: menu,
          ...tippy_menu,
          placement: menu_placement,
          appendTo: document.body,
          theme,
          className: "fastboard-panel",
        }}
      >
        <slot />
      </button>
      <span class="{name}-triangle" />
    </span>
  {:else}
    <button
      class="{name}-btn {className} {theme}"
      class:is-active={active}
      {disabled}
      on:click
      use:tippy={{ content, placement, className }}
    >
      <slot />
    </button>
  {/if}
{:else}
  <button class="{name}-btn {className} {theme}" class:is-active={active} {disabled} on:click>
    <slot />
  </button>
{/if}
