// src/components/PlayerControl/PlayerControl.tsx
import type { Player } from "white-web-sdk";
import type { CommonProps, GenericIcon } from "../../types";

import clsx from "clsx";
import React, { useEffect, useState } from "react";
import RcSlider from "rc-slider";
import { PlayerPhase } from "white-web-sdk";
import { usePlayer } from "./hooks";
import { Icon } from "../../icons";
import { themes, TopOffset } from "../../theme";
import { Icons } from "./icons";
import Tippy from "@tippyjs/react";
import { Button } from "./components/Button";

export type PlayerControlProps = {
  autoHide?: boolean;
  player?: Player;
} & Omit<CommonProps, "room"> &
  GenericIcon<"play" | "pause" | "loading">;

export const name = "fastboard-player-control";

export function PlayerControl({
  autoHide = false,
  player: player_,
  theme = "light",
  i18n,
  ...icons
}: PlayerControlProps) {
  const [currentTime, setCurrentTime] = useState(0);
  const player = usePlayer(player_);

  useEffect(() => {
    setCurrentTime(player.currentTime);
  }, [player.currentTime]);

  useEffect(() => {
    if (player.currentTime !== currentTime) {
      player.seekToProgressTime(currentTime);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTime]);

  const isLoading =
    player.phase === PlayerPhase.WaitingFirstFrame ||
    player.phase === PlayerPhase.Buffering;
  const isPlaying = player.phase === PlayerPhase.Playing;

  const { activeColor } = themes[theme];

  return (
    <div className={clsx(name, theme, { "auto-hide": autoHide })}>
      <button
        className={clsx(
          `${name}-btn`,
          isLoading ? "loading" : isPlaying ? "pause" : "play",
          theme
        )}
        disabled={isLoading}
        onClick={player.togglePlay}
      >
        <Icon
          fallback={
            isLoading ? (
              <Icons.Loading theme={theme} />
            ) : isPlaying ? (
              <Icons.Pause theme={theme} />
            ) : (
              <Icons.Play theme={theme} />
            )
          }
          src={
            isLoading
              ? icons.loadingIcon
              : isPlaying
              ? icons.pauseIcon
              : icons.playIcon
          }
          alt={isLoading ? "[loading]" : isPlaying ? "[pause]" : "[play]"}
        />
      </button>
      <span className={clsx(`${name}-slider`, { loading: isLoading }, theme)}>
        <RcSlider
          disabled={isLoading}
          trackStyle={{ background: activeColor }}
          handleStyle={{ border: `1px solid ${activeColor}` }}
          value={currentTime}
          onChange={setCurrentTime}
          min={0}
          max={player.totalTime}
          step={100}
        />
      </span>
      <span className={clsx(`${name}-current`, theme)}>
        {renderTime(player.currentTime)}
      </span>
      <span className={clsx(`${name}-slash`, theme)}>/</span>
      <span className={clsx(`${name}-total`, theme)}>
        {renderTime(player.totalTime)}
      </span>
      <span className={`${name}-btn-interactive`}>
        <Tippy
          className="fastboard-tip"
          content={renderSpeeds(player)}
          theme={theme}
          placement="top-end"
          trigger="click"
          offset={TopOffset}
          arrow={false}
          interactive
        >
          <Button content={i18n?.t("speed")} theme={theme} disabled={isLoading}>
            <span className={clsx(`${name}-speed-text`, theme)}>
              {player.speed}x
            </span>
          </Button>
        </Tippy>
      </span>
    </div>
  );
}

function renderTime(ms: number) {
  let seconds = ms / 1000;
  let minutes = Math.floor(seconds / 60);
  seconds = Math.floor(seconds) % 60;

  return (
    `${String(minutes).padStart(2, "0")}` +
    `:${String(seconds).padStart(2, "0")}`
  );
}

const Speeds = [2.0, 1.5, 1.25, 1.0, 0.75, 0.5];

function renderSpeeds({
  speed: current,
  setSpeed,
}: {
  speed: number;
  setSpeed: (speed: number) => void;
}) {
  return (
    <div className={clsx(`${name}-panel`, "speed")}>
      {Speeds.map(speed => (
        <button
          className={clsx(`${name}-btn`, "speed", {
            active: speed === current,
          })}
          key={speed}
          onClick={() => setSpeed(speed)}
        >
          {speed}x
        </button>
      ))}
    </div>
  );
}

// packages/fastboard-ui/src/components/PlayerControl/PlayerControl.svelte
<script lang="ts" context="module">
  import type { FastboardPlayer } from "@netless/fastboard-core";
  import type { GenericIcon, I18nData, IconType, Language, Theme } from "../../typings";

  const speeds = [2.0, 1.5, 1.25, 1.0, 0.75, 0.5];

  const i18n: I18nData<"play" | "pause" | "speed"> = {
    en: {
      play: "Play",
      pause: "Pause",
      speed: "Speed",
    },
    "zh-CN": {
      play: "播放",
      pause: "暂停",
      speed: "速度",
    },
  };

  function format(ms: number) {
    const s = Math.floor(ms / 1000);
    const m = Math.floor(s / 60);
    return String(m).padStart(2, "0") + ":" + String(s % 60).padStart(2, "0");
  }
</script>

<script lang="ts">
  import Icon from "../Icon";
  import Icons from "../Icons";
  import Button from "../Button";
  import Slider from "../Toolbar/components/Slider.svelte";

  export let player: FastboardPlayer | null | undefined = null;
  export let theme: Theme = "light";
  export let language: Language = "en";
  export let icons: GenericIcon<"play" | "pause" | "loading"> | undefined = undefined;

  const name = "fastboard-player-control";

  $: t = i18n[language];

  let type: IconType;
  $: type = disabled ? "disable" : "normal";

  $: canPlay = player?.canplay;
  $: disabled = !canPlay;
  $: duration = player?.duration;
  $: current = player?.currentTime;
  $: speed = player?.speed;

  $: phase = player?.phase;
  $: loading = $phase === "waitingFirstFrame" || $phase === "buffering";
  $: playing = $phase === "playing";
  $: className = [loading ? "loading" : "", playing ? "pause" : "play"].filter(Boolean).join(" ");

  let speed_panel: HTMLDivElement;

  function toggle() {
    if (!player) return;
    switch (player.player.phase) {
      case "waitingFirstFrame":
      case "pause":
      case "ended": {
        player.play();
        break;
      }
      case "playing": {
        player.pause();
        break;
      }
    }
  }

  function seek({ detail: seconds }: CustomEvent<number>) {
    if (!player) return;
    player.seek(seconds * 1000);
  }

  function setSpeed(speed: number) {
    if (!player) return;
    player.setSpeed(speed);
  }
</script>

<div class="{name} {theme}">
  <Button
    class={className}
    {name}
    {theme}
    {disabled}
    on:click={toggle}
    content={loading ? "" : playing ? t.pause : t.play}
  >
    {#if loading}
      <Icon src={icons?.loading[type]} alt="[loading]">
        <Icons.Loading {theme} />
      </Icon>
    {:else if playing}
      <Icon src={icons?.pause[type]} alt="[pause]">
        <Icons.Pause {theme} />
      </Icon>
    {:else}
      <Icon src={icons?.play[type]} alt="[play]">
        <Icons.Play {theme} />
      </Icon>
    {/if}
  </Button>
  {#if $current == null || $duration == null || $duration === 0}
    <Slider class="{name}-slider" disabled />
    <span class="{name}-progress loading">&hellip;/&hellip;</span>
  {:else}
    <Slider
      class="{name}-slider"
      {theme}
      value={$current / 1000}
      min={0}
      max={$duration / 1000}
      on:change={seek}
    />
    <span class="{name}-progress">
      <span class="{name}-current">{format($current)}</span>
      <span class="{name}-slash">/</span>
      <span class="{name}-duration">{format($duration)}</span>
    </span>
  {/if}
  <Button
    class="speed"
    {name}
    {theme}
    {disabled}
    content={t.speed}
    menu={speed_panel}
    menu_placement="top-end"
  >
    <span class="{name}-speed-text">{$speed || 1}x</span>
  </Button>
</div>

<div style="display:none">
  <div class="{name}-panel speed" bind:this={speed_panel}>
    {#each speeds as s (s)}
      <Button
        class="speed {s === $speed ? 'is-active' : ''}"
        {name}
        {theme}
        {disabled}
        on:click={() => setSpeed(s)}
      >
        {s}x
      </Button>
    {/each}
  </div>
</div>
