// src/components/PageControl/PageControl.tsx
import type { CommonProps, GenericIcon } from "../../types";

import clsx from "clsx";
import React from "react";
import Tippy from "@tippyjs/react";

import { TopOffset } from "../../theme";
import { Icon } from "../../icons";
import { FilePlus } from "../../icons/FilePlus";
import { ChevronLeft } from "../../icons/ChevronLeft";
import { ChevronRight } from "../../icons/ChevronRight";
import { useWritable } from "../hooks";
import { usePageControl } from "./hooks";

export const name = "fastboard-page-control";

export type PageControlProps = CommonProps &
  GenericIcon<"add" | "prev" | "next">;

export function PageControl({
  room,
  manager,
  theme = "light",
  addIcon,
  addIconDisable,
  prevIcon,
  prevIconDisable,
  nextIcon,
  nextIconDisable,
  i18n,
}: PageControlProps) {
  const writable = useWritable(room);
  const { pageIndex, pageCount, ...actions } = usePageControl(room, manager);

  const disabled = !writable;

  return (
    <div className={clsx(name, theme)}>
      {/* <span className={clsx(`${name}-cut-line`, theme)} />{" "} */}
      <Tippy
        className="fastboard-tip"
        content={i18n?.t("prevPage")}
        theme={theme}
        disabled={disabled}
        placement="top"
        duration={300}
        offset={TopOffset}
      >
        <button
          className={clsx(`${name}-btn`, "prev", theme)}
          disabled={disabled || pageIndex === 0}
          onClick={actions.prevPage}
        >
          <Icon
            fallback={<ChevronLeft theme={theme} />}
            src={disabled ? prevIconDisable : prevIcon}
            alt="[prev]"
          />
        </button>
      </Tippy>
      <span className={clsx(`${name}-page`, theme)}>
        {pageCount === 0 ? "\u2026" : pageIndex + 1}
      </span>
      <span className={clsx(`${name}-slash`, theme)}>/</span>
      <span className={clsx(`${name}-page-count`, theme)}>{pageCount}</span>
      <Tippy
        className="fastboard-tip"
        content={i18n?.t("nextPage")}
        theme={theme}
        disabled={disabled}
        placement="top"
        duration={300}
        offset={TopOffset}
      >
        <button
          className={clsx(`${name}-btn`, "next", theme)}
          disabled={disabled || pageIndex === pageCount - 1}
          onClick={actions.nextPage}
        >
          <Icon
            fallback={<ChevronRight theme={theme} />}
            src={disabled ? nextIconDisable : nextIcon}
            alt="[next]"
          />
        </button>
      </Tippy>
      <Tippy
        className="fastboard-tip"
        content={i18n?.t("addPage")}
        theme={theme}
        disabled={disabled}
        placement="top"
        duration={300}
        offset={TopOffset}
      >
        <button
          className={clsx(`${name}-btn`, "add", theme)}
          disabled={disabled}
          onClick={actions.addPage}
        >
          <Icon
            fallback={<FilePlus theme={theme} />}
            src={disabled ? addIconDisable : addIcon}
            alt="[add]"
          />
        </button>
      </Tippy>
    </div>
  );
}

// packages/fastboard-ui/src/components/PageControl/PageControl.svelte
<script lang="ts" context="module">
  import type { FastboardApp } from "@netless/fastboard-core";
  import type { GenericIcon, I18nData, IconType, Language, Theme } from "../../typings";
  const i18n: I18nData<"prev" | "next" | "add"> = {
    en: {
      prev: "Prev Page",
      next: "Next Page",
      add: "Add Page",
    },
    "zh-CN": {
      prev: "上一页",
      next: "下一页",
      add: "添加页面",
    },
  };
</script>

<script lang="ts">
  import Icon from "../Icon";
  import Icons from "../Icons";
  import Button from "../Button";

  export let app: FastboardApp | null | undefined = null;
  export let theme: Theme = "light";
  export let language: Language = "en";
  export let icons: GenericIcon<"prev" | "next" | "add"> | undefined = undefined;

  const name = "fastboard-page-control";

  $: writable = app?.writable;
  $: disabled = !$writable;
  $: t = i18n[language];

  let type: IconType;
  $: type = disabled ? "disable" : "normal";

  $: index = app?.pageIndex;
  $: length = app?.pageLength;
  $: prev_disabled = disabled || !$index;
  $: next_disabled = disabled || $length == null || $index === $length - 1;

  function prevPage() {
    app?.prevPage();
  }

  function nextPage() {
    app?.nextPage();
  }

  function addPage() {
    app?.addPage({ after: true });
    app?.nextPage();
  }
</script>

<div class="{name} {theme}">
  <Button class="prev" {name} {theme} disabled={prev_disabled} on:click={prevPage} content={t.prev}>
    <Icon src={icons?.prev[type]} alt="[prev]">
      <Icons.Left {theme} />
    </Icon>
  </Button>
  <span class="{name}-text {theme}">
    {#if $index == null || $length == null}
      &hellip;
    {:else}
      {$index + 1}/{$length}
    {/if}
  </span>
  <Button class="next" {name} {theme} disabled={next_disabled} on:click={nextPage} content={t.next}>
    <Icon src={icons?.next[type]} alt="[next]">
      <Icons.Right {theme} />
    </Icon>
  </Button>
  <Button class="add" {name} {theme} {disabled} on:click={addPage} content={t.add}>
    <Icon src={icons?.add[type]} alt="[add]">
      <Icons.WhiteboardAdd {theme} />
    </Icon>
  </Button>
</div>
