// src/components/RedoUndo.tsx
import type { CommonProps, GenericIcon } from "../types";

import clsx from "clsx";
import React, { useCallback, useEffect, useState } from "react";
import { Icon } from "../icons";
import { Undo } from "../icons/Undo";
import { Redo } from "../icons/Redo";

export const name = "fastboard-redo-undo";

export type RedoUndoProps = CommonProps & GenericIcon<"undo" | "redo">;

export function RedoUndo({
  room,
  theme = "light",
  undoIcon,
  undoIconDisable,
  redoIcon,
  redoIconDisable,
}: RedoUndoProps) {
  const [undoSteps, setUndoSteps] = useState(0);
  const [redoSteps, setRedoSteps] = useState(0);

  useEffect(() => {
    if (room) {
      room.isWritable && (room.disableSerialization = false);
      room.callbacks.on("onCanUndoStepsUpdate", setUndoSteps);
      room.callbacks.on("onCanRedoStepsUpdate", setRedoSteps);
      return () => {
        room.callbacks.off("onCanUndoStepsUpdate", setUndoSteps);
        room.callbacks.off("onCanRedoStepsUpdate", setRedoSteps);
      };
    }
  }, [room]);

  return (
    <div className={clsx(name, theme)}>
      <button
        className={clsx(`${name}-btn`, "undo", theme)}
        disabled={undoSteps === 0}
        onClick={useCallback(() => room && room.undo(), [room])}
      >
        <Icon
          theme={theme}
          Fallback={Undo}
          src={undoSteps === 0 ? undoIconDisable : undoIcon}
          alt="[undo]"
        />
      </button>
      <button
        className={clsx(`${name}-btn`, "redo", theme)}
        disabled={redoSteps === 0}
        onClick={useCallback(() => room && room.redo(), [room])}
      >
        <Icon
          theme={theme}
          Fallback={Redo}
          src={redoSteps === 0 ? redoIconDisable : redoIcon}
          alt="[redo]"
        />
      </button>
    </div>
  );
}

// packages/components/src/components/RedoUndo.svelte
<script context="module">
  export const name = "fastboard-redo-undo";
</script>

<script lang="ts">
  import type { Room } from "white-web-sdk";
  import type { RedoUndoProps, Theme } from "../types";
  import { onMount } from "svelte";
  import Icon from "./Icon.svelte";
  import Undo from "../icons/Undo.svelte";
  import Redo from "../icons/Redo.svelte";

  export let room: Room | undefined = undefined;
  export let theme: Theme = "light";

  export let undoIcon: RedoUndoProps["undoIcon"] = undefined;
  export let redoIcon: RedoUndoProps["redoIcon"] = undefined;

  let undoSteps = 0;
  let redoSteps = 0;

  const updateUndoSteps = (e: number) => (undoSteps = e);
  const updateRedoSteps = (e: number) => (redoSteps = e);

  onMount(() => {
    const registerListeners = (room: Room) => {
      room.isWritable && (room.disableSerialization = false);
      room.callbacks.on("onCanUndoStepsUpdate", updateUndoSteps);
      room.callbacks.on("onCanRedoStepsUpdate", updateRedoSteps);
    };

    const removeListeners = (room: Room) => {
      room.callbacks.off("onCanUndoStepsUpdate", updateUndoSteps);
      room.callbacks.off("onCanRedoStepsUpdate", updateRedoSteps);
    };

    room && registerListeners(room);
    return () => room && removeListeners(room);
  });
</script>

<div class="{name} {theme}">
  <button
    class="{name}-item undo"
    disabled={undoSteps === 0}
    on:click={() => room && room.undo()}
  >
    {#if undoIcon}
      <Icon
        icon={undoIcon}
        type={undoSteps === 0 ? "disable" : "normal"}
        alt="[undo]"
      />
    {:else}
      <Undo {theme} />
    {/if}
  </button>
  <button
    class="{name}-item redo"
    disabled={redoSteps === 0}
    on:click={() => room && room.redo()}
  >
    {#if redoIcon}
      <Icon
        icon={redoIcon}
        type={redoSteps === 0 ? "disable" : "normal"}
        alt="[redo]"
      />
    {:else}
      <Redo {theme} />
    {/if}
  </button>
</div>

<style lang="scss">
  $name: "fastboard-redo-undo";
  div {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 5px;
    border-radius: 4px;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.15);
  }
  button {
    appearance: none;
    cursor: pointer;
    margin: 0;
    border: 0;
    padding: 0;
    width: 1em;
    height: 1em;
    background-color: transparent;
    border-radius: 4px;
    font-size: 24px;
    line-height: 1;

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    &:not(:disabled):hover {
      background-color: rgba(51, 129, 255, 0.1);
    }

    :global(svg),
    :global(img) {
      width: 1em;
      height: 1em;
    }
  }
  div.dark {
    background-color: #333;
    border: 1px solid rgba(0, 0, 0, 0.45);

    button:not(:disabled):hover {
      background-color: rgba(51, 129, 255, 0.25);
    }
  }
</style>
