// src/components/ZoomControl.tsx
import type { RoomState } from "white-web-sdk";
import type { CommonProps, GenericIcon } from "../types";

import clsx from "clsx";
import React, { useCallback, useEffect, useState } from "react";
import { clamp } from "../helpers";
import { Icon } from "../icons";
import { Minus } from "../icons/Minus";
import { Plus } from "../icons/Plus";
import { Reset } from "../icons/Reset";

export const name = "fastboard-zoom-control";

export const ScalePoints: readonly number[] = [
  0.10737418240000011, 0.13421772800000012, 0.16777216000000014,
  0.20971520000000016, 0.26214400000000015, 0.3276800000000002,
  0.4096000000000002, 0.5120000000000001, 0.6400000000000001, 0.8, 1, 1.26,
  1.5876000000000001, 2.000376, 2.5204737600000002, 3.1757969376000004,
  4.001504141376, 5.041895218133761, 6.352787974848539, 8.00451284830916, 10,
];

function nextScale(scale: number, delta: 1 | -1) {
  const { length } = ScalePoints;
  const last = length - 1;
  if (scale < ScalePoints[0]) return ScalePoints[0];
  if (scale > ScalePoints[last]) return ScalePoints[last];
  for (let i = 0; i < length; ++i) {
    const curr = ScalePoints[i];
    const prev = i === 0 ? -Infinity : (ScalePoints[i - 1] + curr) / 2;
    const next = i === last ? Infinity : (ScalePoints[i + 1] + curr) / 2;
    if (prev <= scale && scale <= next)
      return ScalePoints[clamp(i + delta, 0, last)];
  }
  return 1;
}

export type ZoomControlProps = CommonProps &
  GenericIcon<"reset" | "minus" | "plus">;

export function ZoomControl({
  room,
  manager,
  theme = "light",
  resetIcon,
  resetIconDisable,
  minusIcon,
  minusIconDisable,
  plusIcon,
  plusIconDisable,
}: ZoomControlProps) {
  const [writable, setWritable] = useState(true);
  const [scale, setScale] = useState(1);

  const resetCamera = useCallback(() => {
    if (room?.isWritable) {
      if (manager) {
        manager.mainView.moveCamera({ scale: 1, centerX: 0, centerY: 0 });
      } else {
        const { scenes, index } = room.state.sceneState;
        if (scenes[index].ppt) {
          room.scalePptToFit();
        } else {
          room.moveCamera({ scale: 1, centerX: 0, centerY: 0 });
        }
      }
    }
  }, [room, manager]);

  const zoomIn = useCallback(() => {
    if (room?.isWritable) {
      if (manager) {
        manager.mainView.moveCamera({
          scale: nextScale(scale, 1),
          centerX: 0,
          centerY: 0,
        });
      } else {
        room.moveCamera({
          scale: nextScale(scale, 1),
          centerX: 0,
          centerY: 0,
        });
      }
    }
  }, [room, manager, scale]);

  const zoomOut = useCallback(() => {
    if (room?.isWritable) {
      if (manager) {
        manager.mainView.moveCamera({
          scale: nextScale(scale, -1),
          centerX: 0,
          centerY: 0,
        });
      } else {
        room.moveCamera({
          scale: nextScale(scale, -1),
          centerX: 0,
          centerY: 0,
        });
      }
    }
  }, [room, manager, scale]);

  useEffect(() => {
    if (room) {
      setWritable(room.isWritable);
      setScale(room.state.cameraState.scale);
    }

    if (manager) {
      setScale(manager.mainView.camera.scale);
    }

    const onRoomStateChanged = (modifyState: Partial<RoomState>) => {
      if (modifyState.cameraState) {
        setScale(modifyState.cameraState.scale);
      }
    };

    const onCameraUpdated = ({ scale }: { scale: number }) => setScale(scale);

    if (room) {
      room.callbacks.on("onEnableWriteNowChanged", setWritable);
      if (manager) {
        manager.mainView.callbacks.on("onCameraUpdated", onCameraUpdated);
      } else {
        room.callbacks.on("onRoomStateChanged", onRoomStateChanged);
      }
    }

    return () => {
      if (room) {
        room.callbacks.off("onEnableWriteNowChanged", setWritable);
        room.callbacks.off("onRoomStateChanged", onRoomStateChanged);
        manager?.mainView.callbacks.off("onCameraUpdated", onCameraUpdated);
      }
    };
  }, [room, manager]);

  const disabled = !writable;

  return (
    <div className={clsx(name, theme)}>
      <button
        className={clsx(`${name}-btn`, "reset", theme)}
        disabled={disabled}
        onClick={resetCamera}
      >
        <Icon
          fallback={<Reset theme={theme} />}
          src={disabled ? resetIconDisable : resetIcon}
          alt="[reset]"
        />
      </button>
      <span className={clsx(`${name}-cut-line`, theme)} />
      <button
        className={clsx(`${name}-btn`, "minus", theme)}
        disabled={disabled}
        onClick={zoomOut}
      >
        <Icon
          fallback={<Minus theme={theme} />}
          src={disabled ? minusIconDisable : minusIcon}
          alt="[minus]"
        />
      </button>
      <span className={clsx(`${name}-scale`, theme)}>
        {Math.ceil(scale * 100)}
      </span>
      <span className={clsx(`${name}-percent`, theme)}>%</span>
      <button
        className={clsx(`${name}-btn`, "plus", theme)}
        disabled={disabled}
        onClick={zoomIn}
      >
        <Icon
          fallback={<Plus theme={theme} />}
          src={disabled ? plusIconDisable : plusIcon}
          alt="[plus]"
        />
      </button>
    </div>
  );
}

// packages/components/src/components/ZoomControl.svelte
<script context="module">
  export const name = "fastboard-zoom-control";
</script>

<script lang="ts">
  import type { WindowManager } from "@netless/window-manager";
  import type { Camera } from "white-web-sdk";
  import type { Theme, ZoomControlProps } from "../types";
  import { onMount } from "svelte";
  import Icon from "./Icon.svelte";
  import Reset from "../icons/Reset.svelte";
  import Less from "../icons/Less.svelte";
  import Plus from "../icons/Plus.svelte";

  export let manager: WindowManager | undefined = undefined;

  export let resetIcon: ZoomControlProps["resetIcon"] = undefined;
  export let lessIcon: ZoomControlProps["lessIcon"] = undefined;
  export let plusIcon: ZoomControlProps["plusIcon"] = undefined;
  export let theme: Theme = "light";

  let scale = 1;

  onMount(() => {
    const cameraListener = (camera: Camera) => (scale = camera.scale);
    manager?.mainView.callbacks.on("onCameraUpdated", cameraListener);
    return () => {
      manager?.mainView.callbacks.off("onCameraUpdated", cameraListener);
    };
  });

  const resetCamera = () => {
    manager?.mainView.moveCamera({
      scale: 1,
      centerX: 0,
      centerY: 0,
    });
  };
</script>

<div class="{name} {theme}">
  <button class="{name} reset" on:click={resetCamera}>
    {#if resetIcon}
      <Icon icon={resetIcon} alt="[reset]" type="normal" />
    {:else}
      <Reset {theme} />
    {/if}
  </button>
  <span class="cut-line {theme}" />
  <button class="{name} less">
    {#if lessIcon}
      <Icon icon={lessIcon} alt="[less]" type="normal" />
    {:else}
      <Less {theme} />
    {/if}
  </button>

  <span>{Math.ceil(scale * 100)}</span> <span class="{name} percent">%</span>

  <button class="{name} plus">
    {#if plusIcon}
      <Icon icon={plusIcon} alt="[plus]" type="normal" />
    {:else}
      <Plus {theme} />
    {/if}
  </button>
</div>

<style lang="scss">
  $name: "fastboard-zoom-control";
  div {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 5px;
    border-radius: 4px;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.15);
  }
  button {
    appearance: none;
    cursor: pointer;
    margin: 0;
    border: 0;
    padding: 0;
    width: 1em;
    height: 1em;
    background-color: transparent;
    border-radius: 4px;
    font-size: 24px;
    line-height: 1;

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    &:not(:disabled):hover {
      background-color: rgba(51, 129, 255, 0.1);
    }

    :global(svg),
    :global(img) {
      width: 1em;
      height: 1em;
    }
  }
  div.dark {
    background-color: #333;
    border: 1px solid rgba(0, 0, 0, 0.45);

    button:not(:disabled):hover {
      background-color: rgba(51, 129, 255, 0.25);
    }
  }
  .cut-line {
    background-color: #e7e7e7;
    height: 24px;
    width: 0.5px;
  }
  .cut-line.dark {
    background-color: rgba(255, 255, 255, 0.15);
  }
  .percent {
    opacity: 0.6;
  }
  span {
    font-size: 12px;
  }
</style>
