// packages/fastboard-ui/src/components/RedoUndo/RedoUndo.svelte
<script lang="ts" context="module">
  import type { FastboardApp } from "@netless/fastboard-core";
  import type { GenericIcon, I18nData, IconType, Language, Theme } from "../../typings";
  const i18n: I18nData<"redo" | "undo"> = {
    en: {
      redo: "Redo",
      undo: "Undo",
    },
    "zh-CN": {
      redo: "重做",
      undo: "撤销",
    },
  };
</script>

<script lang="ts">
  import Icon from "../Icon";
  import Icons from "../Icons";
  import Button from "../Button";

  export let app: FastboardApp | null | undefined = null;
  export let theme: Theme = "light";
  export let language: Language = "en";
  export let icons: GenericIcon<"undo" | "redo"> | undefined = undefined;

  const name = "fastboard-redo-undo";

  $: writable = app?.writable;
  $: disabled = !$writable;
  $: t = i18n[language];

  let type: IconType;
  $: type = disabled ? "disable" : "normal";

  $: undoSteps = app?.canUndoSteps;
  $: redoSteps = app?.canRedoSteps;
  $: undo_disabled = disabled || !$undoSteps;
  $: redo_disabled = disabled || !$redoSteps;

  function undo() {
    app?.undo();
  }

  function redo() {
    app?.redo();
  }
</script>

<div class="{name} {theme}">
  <Button class="undo" {name} {theme} disabled={undo_disabled} on:click={undo} content={t.undo}>
    <Icon src={icons?.undo[type]} alt="[undo]">
      <Icons.Undo {theme} />
    </Icon>
  </Button>
  <Button class="redo" {name} {theme} disabled={redo_disabled} on:click={redo} content={t.redo}>
    <Icon src={icons?.redo[type]} alt="[redo]">
      <Icons.Redo {theme} />
    </Icon>
  </Button>
</div>

// src/components/RedoUndo/RedoUndo.tsx
import type { CommonProps, GenericIcon } from "../../types";

import clsx from "clsx";

import { Icon } from "../../icons";
import { Redo } from "../../icons/Redo";
import { Undo } from "../../icons/Undo";
import { TopOffset } from "../../theme";
import { useWritable } from "../hooks";
import { Tippy } from "../Tippy";
import { useRedoUndo } from "./hooks";

export const name = "fastboard-redo-undo";

export type RedoUndoProps = CommonProps & GenericIcon<"undo" | "redo">;

export function RedoUndo({
  room,
  manager,
  theme = "light",
  undoIcon,
  undoIconDisable,
  redoIcon,
  redoIconDisable,
  i18n,
}: RedoUndoProps) {
  const writable = useWritable(room);
  const { redoSteps, undoSteps, redo, undo } = useRedoUndo(room, manager);

  const disabled = !writable;

  return (
    <div className={clsx(name, theme)}>
      <Tippy
        className="fastboard-tip"
        content={i18n?.t("undo")}
        theme={theme}
        disabled={disabled}
        placement="top"
        delay={[1000, 400]}
        duration={300}
        offset={TopOffset}
      >
        <button
          className={clsx(`${name}-btn`, "undo", theme)}
          disabled={disabled || undoSteps === 0}
          onClick={undo}
        >
          <Icon
            fallback={<Undo theme={theme} />}
            src={undoSteps === 0 ? undoIconDisable : undoIcon}
            alt="[undo]"
          />
        </button>
      </Tippy>
      <Tippy
        className="fastboard-tip"
        content={i18n?.t("redo")}
        theme={theme}
        disabled={disabled}
        placement="top"
        delay={[1000, 400]}
        duration={300}
        offset={TopOffset}
      >
        <button
          className={clsx(`${name}-btn`, "redo", theme)}
          disabled={disabled || redoSteps === 0}
          onClick={redo}
        >
          <Icon
            fallback={<Redo theme={theme} />}
            src={redoSteps === 0 ? redoIconDisable : redoIcon}
            alt="[redo]"
          />
        </button>
      </Tippy>
    </div>
  );
}
