// packages/fastboard-react/src/components/ZoomControl/ZoomControl.tsx
import type { CommonProps, GenericIcon } from "../../typings";

import Tippy from "@tippyjs/react";
import clsx from "clsx";
import React from "react";

import { useTranslation } from "../../i18n";
import { Icon } from "../../icons";
import { Minus } from "../../icons/Minus";
import { Plus } from "../../icons/Plus";
import { Reset } from "../../icons/Reset";
import { TopOffset } from "../../theme";
import { useTheme, useWritable } from "../hooks";
import { useZoomControl } from "./hooks";

export const name = "fastboard-zoom-control";

export type ZoomControlProps = CommonProps & GenericIcon<"reset" | "minus" | "plus">;

export function ZoomControl({
  theme,
  resetIcon,
  resetIconDisable,
  minusIcon,
  minusIconDisable,
  plusIcon,
  plusIconDisable,
}: ZoomControlProps) {
  theme = useTheme(theme);
  const { t } = useTranslation();

  const writable = useWritable();
  const { scale, resetCamera, zoomIn, zoomOut } = useZoomControl();

  const disabled = !writable;

  return (
    <div className={clsx(name, theme)}>
      {/* <span className={clsx(`${name}-cut-line`, theme)} /> */}
      <Tippy
        className="fastboard-tip"
        content={t("zoomOut")}
        theme={theme}
        disabled={disabled}
        placement="top"
        delay={[1000, 400]}
        duration={300}
        offset={TopOffset}
      >
        <button className={clsx(`${name}-btn`, "minus", theme)} disabled={disabled} onClick={zoomOut}>
          <Icon
            fallback={<Minus theme={theme} />}
            src={disabled ? minusIconDisable : minusIcon}
            alt="[minus]"
          />
        </button>
      </Tippy>
      <span className={clsx(`${name}-text`, theme)}>
        <span className={clsx(`${name}-scale`, theme)}>{Math.ceil(scale * 100)}</span>
        <span className={clsx(`${name}-percent`, theme)}>%</span>
      </span>
      <Tippy
        className="fastboard-tip"
        content={t("zoomIn")}
        theme={theme}
        disabled={disabled}
        placement="top"
        delay={[1000, 400]}
        duration={300}
        offset={TopOffset}
      >
        <button className={clsx(`${name}-btn`, "plus", theme)} disabled={disabled} onClick={zoomIn}>
          <Icon fallback={<Plus theme={theme} />} src={disabled ? plusIconDisable : plusIcon} alt="[plus]" />
        </button>
      </Tippy>
      <Tippy
        className="fastboard-tip"
        content={t("reset")}
        theme={theme}
        disabled={disabled}
        placement="top"
        delay={[1000, 400]}
        duration={300}
        offset={TopOffset}
      >
        <button className={clsx(`${name}-btn`, "reset", theme)} disabled={disabled} onClick={resetCamera}>
          <Icon
            fallback={<Reset theme={theme} />}
            src={disabled ? resetIconDisable : resetIcon}
            alt="[reset]"
          />
        </button>
      </Tippy>
    </div>
  );
}

// packages/fastboard-ui/src/components/ZoomControl/ZoomControl.svelte
<script lang="ts" context="module">
  import type { FastboardApp } from "@netless/fastboard-core";
  import type { GenericIcon, I18nData, IconType, Language, Theme } from "../../typings";
  import { clamp } from "../helpers";

  const i18n: I18nData<"plus" | "minus" | "reset"> = {
    en: {
      plus: "Zoom In",
      minus: "Zoom Out",
      reset: "Reset",
    },
    "zh-CN": {
      plus: "放大",
      minus: "缩小",
      reset: "重置",
    },
  };

  const scales: readonly number[] = [
    0.3, 0.4096000000000002, 0.5120000000000001, 0.6400000000000001, 0.8, 1, 1.26, 1.5876000000000001,
    2.000376, 2.5204737600000002, 3,
  ];

  function next_scale(scale: number, delta: 1 | -1) {
    const { length } = scales;
    const last = length - 1;
    if (scale < scales[0]) return scales[0];
    if (scale > scales[last]) return scales[last];
    for (let i = 0; i < length; ++i) {
      const cur = scales[i];
      const prev = i === 0 ? -Infinity : (scales[i - 1] + cur) / 2;
      const next = i === last ? Infinity : (scales[i + 1] + cur) / 2;
      if (prev <= scale && scale <= next) return scales[clamp(i + delta, 0, last)];
    }
    return 1;
  }
</script>

<script lang="ts">
  import Icon from "../Icon";
  import Icons from "../Icons";
  import Button from "../Button";

  export let app: FastboardApp | null | undefined = null;
  export let theme: Theme = "light";
  export let language: Language = "en";
  export let icons: GenericIcon<"plus" | "minus" | "reset"> | undefined = undefined;

  const name = "fastboard-zoom-control";

  $: writable = app?.writable;
  $: disabled = !$writable;
  $: t = i18n[language];

  let type: IconType;
  $: type = disabled ? "disable" : "normal";

  $: camera = app?.camera;
  $: scale = $camera?.scale ?? 1;
  $: plus_disabled = disabled || next_scale(scale, 1) === scale;
  $: minus_disabled = disabled || next_scale(scale, -1) === scale;

  function plus() {
    app?.moveCamera({ scale: next_scale(scale, 1), centerX: 0, centerY: 0 });
  }

  function minus() {
    app?.moveCamera({ scale: next_scale(scale, -1), centerX: 0, centerY: 0 });
  }

  function reset() {
    app?.moveCamera({ scale: 1, centerX: 0, centerY: 0 });
  }
</script>

<div class="{name} {theme}">
  <Button class="plus" {name} {theme} disabled={plus_disabled} on:click={plus} content={t.plus}>
    <Icon src={icons?.plus[type]} alt="[plus]">
      <Icons.Plus {theme} />
    </Icon>
  </Button>
  <span class="{name}-text {theme}">
    {#if $camera == null}
      &hellip;
    {:else}
      {Math.ceil(scale * 100)}%
    {/if}
  </span>
  <Button class="minus" {name} {theme} disabled={minus_disabled} on:click={minus} content={t.minus}>
    <Icon src={icons?.minus[type]} alt="[minus]">
      <Icons.Minus {theme} />
    </Icon>
  </Button>
  <Button class="reset" {name} {theme} {disabled} on:click={reset} content={t.reset}>
    <Icon src={icons?.reset[type]} alt="[reset]">
      <Icons.Reset {theme} />
    </Icon>
  </Button>
</div>
